const UserActionTypes = {
  GOOGLE_SING_IN_START: "GOOGLE_SING_IN_START",
  SING_IN_SUCCESS: "SING_IN_SUCCESS",
  SING_IN_FAILURE: "SING_IN_FAILURE",
  EMAIL_SING_IN_START: "EMAIL_SING_IN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
};

export default UserActionTypes;
